language: php
php:
  - '7.4'
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate:fresh --seed

script:
  - php artisan dusk
  - vendor/bin/phpunit
