language: php
sudo: true
php:
  - '7.4'
services:
  - mysql
addons:
  chrome: stable

install:
  - sudo mysql -e "create database mkmoney"
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp .env.test .env
  - php artisan key:generate
  - php artisan migrate:fresh --seed
  - php artisan dusk:install
  - php artisan dusk:chrome-driver --detect
before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000 &
  - php artisan serve --no-reload &

script:
  - vendor/bin/phpunit
  - php artisan dusk
