language: php
php:
  - '7.4'
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - touch storage/data.db
  - php artisan migrate:fresh --seed
  - php artisan dusk:install

script:
  - vendor/bin/phpunit
  - php artisan dusk
